credentials:
  usernames:
    binowin:
      email: binowin@email.com
      name: Binowin
      password: 'paste_your_hashed_password_here'

cookie:
  name: linx_auth
  key: your_secure_cookie_key
  expiry_days: 30

preauthorized:
  emails:
    - binowin@email.com
